### ISSUE TITLE
Soft-locking upon song loading

### ISSUE THREAD

**Issue by RealSavageJef** [ScoreSpy/Issues#62] opened 2022-07-30 20:11 UTC
**Describe the bug**
If you spam the pause button as you're selecting a song, you will get an infinite black screen

**To Reproduce**
Spam pause the moment you've readied

**Comment by Stickheadz32** [comment] 2022-07-30 22:54
I think doing this opens up some kind of start menu during blackscreen, in which you can close by pressing red (a few times), and then the game stops blackscreening and resumes to normal.

**Comment by Ahriana** [comment] 2022-08-14 04:47
has this been verified to be a scorespy only issue?

**Comment by Ahriana** [comment] 2022-08-14 04:52
dupe of https://github.com/ScoreSpy/Issues/issues/14

**Closed as completed by Ahriana** 2022-08-14 04:52 UTC
Labels: help wanted, question, bug investigation
