### ISSUE TITLE
Game freezing upon quitting, resulting in force closing or ending task

### ISSUE THREAD

**Issue by RealSavageJef** [ScoreSpy/Issues#22] opened 2022-07-07 04:54 UTC

**Comment by Ahriana** [comment] 2022-07-11 03:14
if anyone can find a reliable way to reproduce this please let me know.

**Comment by Ahriana** [comment] 2022-07-11 03:42
dupe of https://github.com/ScoreSpy/Issues/issues/13

**Closed as completed by Ahriana** 2022-07-11 03:42 UTC
Labels: bug, help wanted, cant replicate, bug investigation
